### PR TITLE
Fix Quilt incompatibility

### PR DESCRIPTION
**Pull request by SzczurekYT**
Solves #21.
You asked for a PR so here you go.
Note that I made this using github web editor so I didn't have any checks, but it should work.
I also removed this line
```java
@Shadow public abstract TypedActionResult<ItemStack> use(World world, PlayerEntity user, Hand hand);
```
because it wasn't used anywhere, and was probably added by your IDE by accident.

### CODE REVIEW

**Comment by dsfhdshdjtsb** [comment]
Ur solution didn't work on my end when I copy pasted, was hoping that you could run it on ur IDE and then make a pull request if you got it to work?

**Comment by SzczurekYT** [comment]
I'm don't have time today, but will check this out soon :)

**Comment by SzczurekYT** [comment]
> Ur solution didn't work on my end when I copy pasted, was hoping that you could run it on ur IDE and then make a pull request if you got it to work?

I ran that in my IDE, added a missing import and it works.
The copy paste code is perfectly fine.
Your IDE will complain because MinecraftDev plugin has a bug and sometimes it says a mixin is incorrect while it is.
Soy you will have this red underline 
image
but the code is correct and everything works (tested on quilt and in dev env).
You can add a `@SuppressWarnings("InvalidInjectorMethodSignature")` to remove the warning if you want. Like this
image

**Comment by SzczurekYT** [comment]
This is redy to be merged.

**Comment by SzczurekYT** [comment]
@dsfhdshdjtsb

**Comment by dsfhdshdjtsb** [comment]
Late response, but thanks. According to the docs the return type and the type of the singular parameter should match, so having the extra parameters is probably making the mcdev plugin throw an error. Works fine with the error suppressed so whatever. This will be implemented in the next release for 1.20.2 (whenever that comes out)

**Pull request merged**
